version: '3.3'

services:
  csgodashboardrank:
    container_name: csgodashboardrank
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - database
    command: bash -c 'yarn migration:run && yarn dev'
  database:
    container_name: database
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432