version: '3.7'

services:
  csgodatabase:
    container_name: csgodatabase
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432

  migration:
    build: .
    env_file: .env
    command:
        bash -c 'while !</dev/tcp/csgodatabase/5432; do sleep 1; done; yarn migration:run'
    volumes:
        - ./src:/app/src
    depends_on:
        - csgodatabase

  csgodashboardrank:
    container_name: csgodashboardrank
    build:
      context: .
      dockerfile: Dockerfile
    command:
        bash -c 'while !</dev/tcp/csgodatabase/5432; do sleep 1; done; yarn dev'
    env_file: .env
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - csgodatabase
      - migration